### PR TITLE
Person abstract class

### PR DESCRIPTION
**Pull request by MyllaCastro**
- Adding Person's class
- Moving tests/ folder to ProjectManagementSystem.Tests/ folder to follow guidelines
- Adding basic Unit Test using xUnit

image

JIRA:

https://dreamteam2.atlassian.net/browse/SCRUM-6

### CODE REVIEW

**Review by Cngomides — CHANGES_REQUESTED** [review]
It would be good to have a solution to link both projects. I guess you might missed pushing it.

**Comment by MyllaCastro** [comment]
> It would be good to have a solution to link both projects. I guess you might missed pushing it.

I did a quick search here and I think what you mean by "a solution" is a solution file .sln right? I'll do that. Thank you!

**Comment by Cngomides** [comment]
> > It would be good to have a solution to link both projects. I guess you might missed pushing it.
> 
> I did a quick search here and I think what you mean by "a solution" is a solution file .sln right? I'll do that. Thank you!

It is exactly what I mean. Thanks!

**Comment by Cngomides** [comment]
Looks good now.

**Pull request merged**
